### ISSUE TITLE
vcf conversion

### ISSUE THREAD

**Issue by priyambial123** [SamuelNicaise/variantconvert#20]
Hello

I ran this command:

`/GROUP/AnnotSV/bin/AnnotSV -SVinputfile "/GROUP/temp_pacbio/cohorts/bipolar_rerun_secondcleanup/pbsv/shared_hetero_dp_S3.vcf" -genomeBuild GRCh38 -SVminSize 1 -vcf 1`

I couldn't save the output as vcf. Please find the below log report. Can you help me to fix this issue

```
main_cols: ['SV_chrom', 'SV_start', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER']
2023-03-28 16:34:20 [INFO] Converting to vcf from tsv using config: /AnnotSV/share/python3/variantconvert/configs/config_annotsv3_from_vcf_GRCh38.json
Traceback (most recent call last):
  File "/miniconda3/envs/varconvert/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/envs/varconvert/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/AnnotSV/share/python3/variantconvert/variantconvert/__main__.py", line 191, in <module>
    main()
  File "/AnnotSV/share/python3/variantconvert/variantconvert/__main__.py", line 187, in main
    main_convert(args)
  File "/AnnotSV/share/python3/variantconvert/variantconvert/__main__.py", line 79, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/AnnotSV/share/python3/variantconvert/variantconvert/converters/vcf_from_annotsv.py", line 326, in convert
    info_dic = self._build_info_dic()
  File "/AnnotSV/share/python3/variantconvert/variantconvert/converters/vcf_from_annotsv.py", line 187, in _build_info_dic
    merged_annots = self._merge_full_and_split(df_variant)
  File "/AnnotSV/share/python3/variantconvert/variantconvert/converters/vcf_from_annotsv.py", line 140, in _merge_full_and_split
    raise ValueError(
ValueError: Each variant is assumed to only have one single line of 'full' annotation

```

Thank you

**Comment by priyambial123** [comment]
Can you share your mail ID, I will share the file

Thank you

**Comment by SamuelNicaise** [comment]
You can send it at samuel.nicaise {@} chru-strasbourg {dot} fr

**Comment by JbaptisteLam** [comment]
Hi @priyambial123,
We are still under investigation but it appears that your input VCF contains duplicate variations (almost 60) which is not allowed, they should be merge into once,
After duplicate removal try it with AnnotSV 3.2.3, it should work as expected :)

**Comment by JbaptisteLam** [comment]
I will send you the vcf without duplicate and some examples,
We will have a look to this too, thanks for noticing it
