### ISSUE TITLE
Error when trying to convert to VCF in AnnotSV

### ISSUE THREAD

**Issue by nvnieuwk** [SamuelNicaise/variantconvert#22]
I've had some problems trying to convert the output of AnnotSV to a VCF format (as mentioned in this [issue](https://github.com/lgmgeo/AnnotSV/issues/168)). They asked me to repost the issue here:

Hi,

I'm trying to run the tool with the `-vcf 1` option, but am getting TSV files as output instead of VCF files. Am I doing something wrong or is this feature not fully implemented yet?

Command:
```bash
AnnotSV \
    -annotationsDir AnnotSV \
    -outputFile test.vcf \
    -SVinputFile sv_query.vcf.gz \
    -vcf 1
```

Output folder:
```
├── 20230403_AnnotSV
├── AnnotSV -> /home/nvnieuwk/Documents/data/AnnotSV/share/AnnotSV
├── sv_query.vcf.gz -> /tmp/tmp8i_0jtyz/stage-b63e3e39-fa0c-456c-b890-5684c6f7b0c2/33/9f416cecabdc1793bb044e8cec64bd/sv_query.vcf.gz
├── sv_query.vcf.gz.tbi -> /tmp/tmp8i_0jtyz/stage-b63e3e39-fa0c-456c-b890-5684c6f7b0c2/27/9c146bee77905d49f0f78b47066e00/sv_query.vcf.gz.tbi
├── test.vcf.tsv
├── test.vcf.unannotated.tsv
└── test.vcf.variantconvert.log
```

Variantconvert log:
```log
python3 /tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert convert -i 20230403_AnnotSV/test.vcf.tsv -o 20230403_AnnotSV/test.vcf.vcf -fi annotsv -fo vcf -c /tmp/AnnotSV-3.3.2/share/python3/variantconvert/configs/GRCh38/annotsv3_from_vcf.json

2023-04-03 13:29:16 [INFO] running variantconvert 1.2.2
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert/__main__.py", line 226, in <module>
    main()
  File "/tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert/__main__.py", line 209, in main
    main_convert(args)
  File "/tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert/__main__.py", line 74, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert/converters/vcf_from_annotsv.py", line 460, in convert
    self.sample_list = self._get_sample_list()
  File "/tmp/AnnotSV-3.3.2/share/python3/variantconvert/variantconvert/converters/vcf_from_annotsv.py", line 76, in _get_sample_list
    raise ValueError(
ValueError: 0      When using an AnnotSV file generated from a VC...
1      When using an AnnotSV file generated from a VC...
2      When using an AnnotSV file generated from a VC...
3      When using an AnnotSV file generated from a VC...
4      When using an AnnotSV file generated from a VC...
                             ...                        
475    When using an AnnotSV file generated from a VC...
476    When using an AnnotSV file generated from a VC...
477    When using an AnnotSV file generated from a VC...
478    When using an AnnotSV file generated from a VC...
479    When using an AnnotSV file generated from a VC...
Name: Samples_ID, Length: 480, dtype: object
```

Thanks in advance
-Nicolas

**Comment by steven-solar** [comment]
I'm having a similar problem. I ran
```
$ANNOTSV/bin/AnnotSV \
    -genomeBuild GRCh38 \
     -vcf 1 \
    -SVinputInfo 1 \
    -includeCI 0 \
    -SVinputFile inputs/$proband.$tool.vcf \
    -outputFile outputs/$proband.$tool.annotsv.vcf
```
And see an output of `<proband>.hificnv.ann.vcf.vcf.tsv` that contains the following:
```
python3 /path/to/AnnotSV/share/python3/variantconvert/variantconvert convert -i <proband>.hificnv.annotsv.vcf.tsv -o <proband>.hificnv.ann.vcf.vcf.tsv -fi annotsv -fo vcf -c /path/toj/AnnotSV/share/python3/variantconvert/configs/GRCh38/annotsv3_from_vcf.json

2023-04-03 16:50:40 [INFO] running variantconvert 1.2.2
2023-04-03 16:50:42 [INFO] variantconvert finished.
````

**Comment by lgmgeo** [comment]
AnnotSV usage: 

> -outputFile $proband.$tool.annotsv.vcf
> And see an output of <proband>.hificnv.ann.vcf.vcf.tsv that contains the following:

Just to let you know, you need to run AnnotSV with:
`-outputFile $proband.$tool.annotated.tsv`

- The `$proband.$tool.annotated.tsv` file will be created by AnnotSV.
- Then, with the `-vcf 1` option, this TSV file will be converted to VCF by variantconvert (`$proband.$tool.annotated.vcf`).
`$proband.$tool.annotated.variantconvert.log` will be the variantconvert log file. 
I'm quite surprised that in your case this file is called ` <proband>.hificnv.ann.vcf.vcf.tsv`

**Comment by lgmgeo** [comment]
@nvnieuwk 
Solve in https://github.com/lgmgeo/AnnotSV/issues/168

**Comment by nvnieuwk** [comment]
It could maybe be useful to add some kind of error message if the VCF is badly formatted :)

**Comment by nvnieuwk** [comment]
Thank you!

**Comment by lgmgeo** [comment]
Will be present in the next AnnotSV release.
Can you close this issue?
