### ISSUE TITLE
error when converting annotsv tsv to vcf

### ISSUE THREAD

**Issue by SplitInf** [SamuelNicaise/variantconvert#26]
Hi, Thanks for making this useful tool available!

I have ran into issue trying to convert annotsv tsv file to vcf with variantconvert. I am using AnnotSV 3.3.5 and the latest variantconvert.

my commands:

`variantconvert -i sample.annotated.tsv -o sample.annotated.vcf -fi tsv -fo vcf -c /path/hg19/annotsv3_from_vcf.json`

The error seems to indicate unmatched header? DD_status is not found in the output tsv file in recent AnnotSV versions.

```
2023-06-14 03:12:23 [INFO] running variantconvert 1.2.2
Traceback (most recent call last):
  File "/variantconvert/variantconvert/__main__.py", line 226, in <module>
    main()
  File "/variantconvert/variantconvert/__main__.py", line 209, in main
    main_convert(args)
  File "/variantconvert/variantconvert/__main__.py", line 74, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/variantconvert/variantconvert/converters/vcf_from_tsv.py", line 122, in convert
    s = vcf_col + "=" + data[tsv_col][i]
KeyError: 'DDD_status'
```

**Comment by SamuelNicaise** [comment]
Hi, thanks for using this tool.

An unmatched header should not cause a crash. Could you please share an example of an input tsv file causing the issue?

**Comment by SplitInf** [comment]
Thank you for your response and your help in looking into this. 

here's an example input tsv file (added *.txt to get around github upload requirement)
[dummy.annotated.tsv.txt](https://github.com/SamuelNicaise/variantconvert/files/12411138/dummy.annotated.tsv.txt)

Unfortunately it's been awhile since I worked on this I am unable to reproduce the same error code. But I'm positive the workflow was vcf -> annotsv -> variantconvert 
Right now the error is

```
2023-08-22 13:11:31 [INFO] running variantconvert 1.2.2
Traceback (most recent call last):
  File "/variantconvert/variantconvert/__main__.py", line 226, in <module>
    main()
  File "/variantconvert/variantconvert/__main__.py", line 209, in main
    main_convert(args)
  File "/variantconvert/variantconvert/__main__.py", line 74, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/variantconvert/variantconvert/converters/vcf_from_tsv.py", line 128, in convert
    for vcf_col, tsv_col in self.config["VCF_COLUMNS"]["FORMAT"].items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by SamuelNicaise** [comment]
Running the current master branch version and configs, I had no errors: 

variantconvert convert -i dummy.annotated.tsv.txt -o dummy.vcf.txt -fi annotsv -fo vcf -c configs/hg19/annotsv3_from_bed.json

[dummy.vcf.txt](https://github.com/SamuelNicaise/variantconvert/files/12430557/dummy.vcf.txt)

Whatever the issue was, it seems solved in the current version. It will be implemented in the next version of AnnotSV which is currently in development. 


--

If you can't wait for the next version of AnnotSV: 
- are you using a separate install of variantconvert or the one included in AnnotSV? If the former, which commit? 
- can you send the config file you're using?

**Comment by SplitInf** [comment]
Thanks for the command and for looking into this. The problem is solved!
