### ISSUE TITLE
Error when converting tsv to vcf with one sample only

### ISSUE THREAD

**Issue by lavauxt** [SamuelNicaise/variantconvert#28]
hello
when i tried to convert a tsv with only one sample, i got this error 👍 
Traceback (most recent call last):
  File "/opt/conda/bin/variantconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/variantconvert/src/variantconvert/__main__.py", line 226, in main
    main_convert(args)
  File "/usr/lib/variantconvert/src/variantconvert/__main__.py", line 75, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/usr/lib/variantconvert/src/variantconvert/./converters/vcf_from_tsv.py", line 140, in convert
    sample_field.append(data[val][index])
UnboundLocalError: local variable 'index' referenced before assignment

Seems that index is not defined in the monosample part of the tsv to vcf py file

**Comment by SamuelNicaise** [comment]
Fixed in the next version
